### ISSUE TITLE
'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:alt_bloc/src/router.dart'

### ISSUE THREAD

**Issue by nicksav** [dashdevs/alt_bloc#22]
Running Gradle task 'assembleRelease'...                        
../programs/flutter/.pub-cache/hosted/pub.dartlang.org/alt_bloc-1.0.0+1/lib/src/bloc_provider.dart:6:1: Error: 'Router' is imported from both 'package:flutter/src/widgets/router.dart' and 'package:alt_bloc/src/router.dart'.

Guys started to have issues with this error. 
Any idea?

**Comment by nicksav** [comment]
This error is on 1.22.0

**Comment by EgorLogachev** [comment]
Hi @nicksav.

**Comment by EgorLogachev** [comment]
Hi @nicksav.
